### ISSUE TITLE
Installation instructions should mention 'mark of the web'

### ISSUE THREAD

**Issue by HughWarrington** [joyfullservice/msaccess-vcs-addin#539] opened 2024-10-11 14:55 UTC
I think under typical circumstances (at least in my testing with a clean install of Office 365 on a new Win11 VM) you will be blocked from installing the add-in due to Access deciding not to trust something the user just downloaded.

![image](https://github.com/user-attachments/assets/62f93927-8b61-420d-963f-0d6707ef1167)

I think [this](https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Quick-Start#install-add-in) needs updating to add a step. Actually there are already great instructions on [this blog](https://nolongerset.com/install-vcs-addin/). I suggest to copy what that blog says (and/or just link to it?).

As it happens I only found that blog after working out my own solution in PowerShell:

```
PS C:\Users\User\Downloads> Remove-Item -Path '.\Version Control.accda' -Stream Zone.Identifier -ErrorAction Stop
```

**Comment by hecon5** [comment] 2024-10-21 13:37
Huh. So, I was going to update the screenshots for this, but apparently I don't get the MOTW on my machine! 

@HughWarrington: Can you post the screenshots for where you see MOTW? 

I briefly considered just using @mwolfe02 images... but that's his private blog and I don't know that it's right to steal his imagery and second, the screenshot doesn't match the instruction "colors" and theme from the rest of the wiki.

**Comment by mwolfe02** [comment] 2024-10-21 13:58
@hecon5 I've got no issue with you using the screenshots from my blog as long as there is a link back to the original article.

**Comment by mwolfe02** [comment] 2024-10-21 14:00
> apparently I don't get the MOTW on my machine!

FYI, if you use 7-zip to extract files from the zip folder, it (by design) does not maintain the MOTW on the extracted files.  The built-in Windows zip utility does.

**Comment by hecon5** [comment] 2024-10-21 14:03
> @hecon5 I've got no issue with you using the screenshots from my blog as long as there is a link back to the original article.

@mwolfe02: Thanks! I never want to assume such a thing, as it drives me batty when I see stolen content, even for something open source like this project.

> > apparently I don't get the MOTW on my machine!
> 
> FYI, if you use 7-zip to extract files from the zip folder, it (by design) does not maintain the MOTW on the extracted files. The built-in Windows zip utility does.

Huh! I did not know that; I in fact did use 7Zip to extract! I'll redownload and try again.

**Comment by mwolfe02** [comment] 2024-10-21 15:44
[Mark of the Web (MOTW) Support Among Zip Utilities](https://nolongerset.com/motw-zip-support/)

**Comment by hecon5** [comment] 2024-10-22 19:30
@HughWarrington: with PR #550 this was added. If the updated info meets your needs, can you close this?

**Closed** 2024-10-24 09:54 UTC
