### ISSUE TITLE
'Build from source' unexpectedly does nothing

### ISSUE THREAD

**Issue by HughWarrington** [joyfullservice/msaccess-vcs-addin#542] opened 2024-10-14 12:25 UTC
I'm using addin version 4.0.34, Office 365 64-bit, Win10 64-bit.

I may have misunderstood what this button is supposed to do (I'm basing my expectations on https://github.com/joyfullservice/msaccess-vcs-addin/discussions/405). Here's what I did:

1. Open my .mdb.
2. Click _Open Add-in_ ribbon button.
3. Click _Export All Source_.
4. Copy the new .src folder that was produced to another machine. I copied every file _except_ vcs-index.json, based on my reasoning from https://github.com/joyfullservice/msaccess-vcs-addin/discussions/541, although I get the same result whether or not I do that.
5. Open Access on the other machine.
6. Open and close a random other database file so that I have access to the Version Control ribbon.
7. Click _Build From Source_ and select the .src folder copied over to this machine.
8. An import runs in 0.14 seconds and apparently finds nothing in the source folder at all. [Build.log](https://github.com/user-attachments/files/17363897/Build.log) attached.

If instead I click _Build As..._, choose the same source folder, and pick an arbitrary name 'foo.mdb' then the folder content is picked up correctly, and the full DB is built.

Have I misunderstood what 'Build from source' is supposed to do?

**Comment by joyfullservice** [comment] 2024-10-14 16:24
That should work, assuming you are using a relative build path. (I typically leave the export path blank in options. That way it exports to a subfolder relative to the current database, and the resulting source folder is portable and can be built from any location.)

![image](https://github.com/user-attachments/assets/3a16f7a2-8ff7-49cb-a6fc-4fb9ecdf4fb1)

Also, you should be able to click the "Build From Source" button on a fresh Access Instance without having to open another database first. This was something I worked through a little while back.

Let me know if you find out any more clues on this. I just tested copying the source folder to another location on my computer, and I was able to build just fine in the new location by selecting the source folder. 🤔

**Comment by HughWarrington** [comment] 2024-10-15 13:52
Huh. I get the same behaviour on two different exports which I am rebuilding from. It doesn't really matter because I can use the _Build As..._ option every time and just enter the name, it's almost as fast.

> Also, you should be able to click the "Build From Source" button on a fresh Access Instance without having to open another database first. This was something I worked through a little while back.

Maybe I am missing something, but when I start Access it looks like this:

![image](https://github.com/user-attachments/assets/2b78fd2a-b105-417c-8b1f-f9fb0d2a6d26)

There's no way to get to the ribbon without first opening a file, unless I'm missing something!

**Comment by joyfullservice** [comment] 2024-10-15 15:18
Thanks for the screen shot... Access 2010 looks like this:

![image](https://github.com/user-attachments/assets/90e75f35-b37a-4263-8cc7-14ac9cd00465)

It appears that they tried to simplify the interface on startup. Oh well. I am open to any suggestions on making the initial launch easier in Access 365.

**Comment by HughWarrington** [comment] 2024-10-15 18:27
@bclothier nice! 🙏

**Comment by HughWarrington** [comment] 2024-10-22 15:58
Regarding my original report, I have a workaround, and the impact is very low in any case. Probably not worth the effort to investigate further. From my perspective, feel free to close this as a WONTFIX.

**Comment by hecon5** [comment] 2024-10-22 19:31
@HughWarrington: if you're satisfied, you can close this, too.

**Comment by joyfullservice** [comment] 2024-10-22 21:49
I am not able to reproduce the issue, so I will close the issue for now. We can always reopen it if the problem becomes more clear.

**Closed** 2024-10-22 21:49 UTC
Labels: need more details
