### ISSUE TITLE
VCS crashes in Citrix environment

### ISSUE THREAD

**Issue by sotalvaro** [joyfullservice/msaccess-vcs-addin#439] opened 2023-09-19 15:36 UTC
Hi Adam thanks for this great tool, I have another problem, I have a Virtual Machine in azure works very well with the VCS, but I have another VM production environment in Citrix and in this system the VCS always crashes when I tried execute anything there.

**Comment by joyfullservice** [comment] 2023-09-20 18:08
I am not personally very familiar with the Citrix environment, but I would recommend that you check the reference libraries in VBA to make sure they are all available on that machine.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/daf1753d-629d-4528-9a81-3325ad8ef530)

Second, you will need to review the [security settings](https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Security-Considerations) in that environment to ensure that the add-in has the ability to perform its intended functions.

Development environment configurations are something very specific to each developer/organization, so you are probably best off working through these things with your IT team based on the information provided in the above [link](https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Security-Considerations).

**Comment by joyfullservice** [comment] 2023-09-22 13:47
Yes, they should automatically resolve to the installed version.

**Comment by sotalvaro** [comment] 2023-09-22 14:25
> Yes, they should automatically resolve to the installed version.

And I don't find the Microsoft forms 2.0 objects library, I will find problems if don't find it?

**Comment by sotalvaro** [comment] 2023-09-22 16:21
Adam I always get this error message when I tried to build from source and build as, build everything until arrive to the forms, in the forms immediately crashes 
<img width="520" alt="image" src="https://github.com/joyfullservice/msaccess-vcs-addin/assets/138826677/d5f9ea03-0227-4d56-a03c-28ae0137c3d2">
I check all the specifications that you bring me in the previously comments(references and trusted things) but still don't working (just i don't find the Microsoft forms 2.0 objects library), any other idea adam? because this same files in my local laptop or in other environments build successful, I check the other environments and any of them have this library Microsoft forms 2.0 objects

**Comment by sotalvaro** [comment] 2023-09-22 16:21
> Adam I always get this error message when I tried to build from source and build as, build everything until arrive to the forms, in the forms immediately crashes <img alt="image" width="520" src="https://user-images.githubusercontent.com/138826677/269996293-d5f9ea03-0227-4d56-a03c-28ae0137c3d2.png"> I check all the specifications that you bring me in the previously comments(references and trusted things) but still don't working (just i don't find the Microsoft forms 2.0 objects library), any other idea adam? because this same files in my local laptop or in other environments build successful, I check the other environments and any of them have this library Microsoft forms 2.0 objects



> I am not personally very familiar with the Citrix environment, but I would recommend that you check the reference libraries in VBA to make sure they are all available on that machine.
> 
> ![image](https://user-images.githubusercontent.com/7254992/269376117-daf1753d-629d-4528-9a81-3325ad8ef530.png)
> 
> Second, you will need to review the [security settings](https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Security-Considerations) in that environment to ensure that the add-in has the ability to perform its intended functions.
> 
> Development environment configurations are something very specific to each developer/organization, so you are probably best off working through these things with your IT team based on the information provided in the above [link](https://github.com/joyfullservice/msaccess-vcs-addin/wiki/Security-Considerations).

**Comment by sotalvaro** [comment] 2023-09-22 19:51
I checked everything adam even all the security advices that you bring in the links, I found the microsoft forms 2.0 objects library and still crashes adam

**Comment by joyfullservice** [comment] 2023-09-22 22:32
I am not sure what is causing the crash for you on the Citrix system. I would suggest trying to do some troubleshooting where you start with a very simple database with one form, and see if you can build that. If you can build a very simple database, then keep introducing the other items from your main database piece by piece until you can identify which change causes the crash. (For example, try removing the forms from the database, and see if you can build it without the forms. Then add the forms one or a few at a time to see if it is a specific form that is triggering the crash.) This will give you something to look at in more detail to see if you can figure out what might be causing the crash.

**Comment by sotalvaro** [comment] 2023-09-28 15:19
Hey adam may you have an idea to fix them?

**Comment by joyfullservice** [comment] 2023-10-02 15:18
@sotalvaro - This may not be related to the add-in, but to an issue with Access, Citrix, and something with the specific form that you are dealing with. To confirm this, you could use the following code in the immediate window on this database in the Citrix environment. (This would run the native commands directly, independent of the VCS add-in.)

```vba
SaveAsText acForm, "frmContractActivityDurationPerformanceByActivity", "Test"
' Then manually delete the existing form before running the following line
LoadFromText acForm, "frmContractActivityDurationPerformanceByActivity", "Test"
```

If you encounter the crash when running the LoadFromText line, that will confirm that this is technically not an issue with the add-in. Obviously this is a problem you would probably still like to solve, so here is a suggestion on how to proceed with the troubleshooting if the crash still occurs when using the native commands directly from the immediate window.

Essentially, you need to pinpoint something on the form that is causing the crash. It could be a specific control or property that is somehow triggering the crash. The fact that some forms import successfully tells you that there is something specific with this form. You could make a copy of the form, open it in design view, then delete all the controls, save the form and try again. If that works, then try deleting half of the controls. Keep isolating the factors until you can pinpoint exactly what is causing the crash. It might be that you could recreate the offending control or something like that.

I don't know why it would just be crashing in the Citrix environment, but perhaps your troubleshooting will uncover some additional clues in the process. You may find additional clues/tips on [Citrix](https://discussions.citrix.com/topic/409370-app-crashes-if-started-from-within-citrix-remote-pc-session-but-if-started-local-and-connecting-later-the-app-runs/) forums.

**Comment by joyfullservice** [comment] 2024-02-06 19:48
This seems to be more of an environment-specific issue that I am unable to reproduce. We can reopen this if more details arise, but for now I am closing this as out of scope for this project.

**Closed by joyfullservice** 2024-02-06 19:48 UTC
Labels: out of scope
